language: rust
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - gcc-4.4
    - gcc-4.6
    - gcc-4.7
    - gcc-4.8
    - clang-3.4
    - clang-3.5
    - clang-3.6
    - clang-3.8
    - clang-3.9

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - make travis
