#!/bin/bash -eux
OUT="$1"

compilers=$(echo /usr/bin/gcc-[0-9]* /usr/bin/clang-[0-9]*)

pushd test
for CC in $compilers; do
  cc=$(basename ${CC})

  FORTIFY="-O1 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1"
  NO_FORTIFY="-O1 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" 

  for static_flag in "" "-static"; do
    # Not all compiler versions support --pie/--no-pie, so silently fail here
    ${CC} $static_flag --pie nop.c -o "$OUT/elf-${cc}-pie${static_flag}" || :
    ${CC} $static_flag --no-pie nop.c -o "$OUT/elf-${cc}-no-pie${static_flag}" || :

    ${CC} $static_flag -z execstack nop.c -o "$OUT/elf-${cc}-execstack"

    ${CC} $static_flag $NO_FORTIFY strcpy.c -c -o strcpy.o
    ${CC} $static_flag $NO_FORTIFY copy.c strcpy.o -o "$OUT/elf-${cc}-missing-fortify${static_flag}"

    ${CC} $static_flag $NO_FORTIFY strcpy.c -c -o strcpy.o
    ${CC} $static_flag $FORTIFY copy.c strcpy.o -o "$OUT/elf-${cc}-partial-fortify${static_flag}"

    ${CC} $static_flag $FORTIFY strcpy.c -c -o strcpy.o
    ${CC} $static_flag $FORTIFY copy.c strcpy.o -o "$OUT/elf-${cc}-full-fortify${static_flag}"

    ${CC} $static_flag -fno-stack-protector copy.c -o "$OUT/elf-${cc}-no-stack-protector${static_flag}"
    ${CC} $static_flag -fstack-protector copy.c -o "$OUT/elf-${cc}-stack-protector${static_flag}"

  done

  for x in $OUT/elf*-static; do
    strip -o "${x}-stripped" "$x"
  done

  ${CC} -Wl,-rpath,"/foo" nop.c -o "$OUT/elf-${cc}-rpath"
  ${CC} -Wl,-rpath,"/bar",--enable-new-dtags nop.c -o "$OUT/elf-${cc}-runpath"

  ${CC} -fPIC $NO_FORTIFY strcpy.c -c -o strcpy.o
  ${CC} -fPIC -shared $NO_FORTIFY copy.c strcpy.o -o "$OUT/elf-${cc}-missing-fortify.so"

  ${CC} -fPIC $NO_FORTIFY strcpy.c -c -o strcpy.o
  ${CC} -fPIC -shared $FORTIFY copy.c strcpy.o -o "$OUT/elf-${cc}-partial-fortify.so"

  ${CC} -fPIC $FORTIFY strcpy.c -c -o strcpy.o
  ${CC} -fPIC -shared $FORTIFY copy.c strcpy.o -o "$OUT/elf-${cc}-full-fortify.so"

  ${CC} -fPIC -shared -fno-stack-protector copy.c -o "$OUT/elf-${cc}-no-stack-protector.so"
  ${CC} -fPIC -shared -fstack-protector copy.c -o "$OUT/elf-${cc}-stack-protector.so"


  ${CC} $NO_FORTIFY -c strcpy.c -o strcpy.o
  ${CC} $NO_FORTIFY -c copy.c -o copy.o
  ar cr "$OUT/elf-${cc}-missing-fortify.a" copy.o strcpy.o

  ${CC} $NO_FORTIFY -c strcpy.c -o strcpy.o
  ${CC} $FORTIFY -c copy.c -o copy.o
  ar cr "$OUT/elf-${cc}-partial-fortify.a" copy.o strcpy.o

  ${CC} $FORTIFY -c strcpy.c -o strcpy.o
  ${CC} $FORTIFY -c copy.c -o copy.o
  ar cr "$OUT/elf-${cc}-full-fortify.a" copy.o strcpy.o

  ${CC} -fno-stack-protector -c copy.c -o copy.o
  ar cr "$OUT/elf-${cc}-no-stack-protector.a" copy.o

  ${CC} -fstack-protector -c copy.c -o copy.o
  ar cr "$OUT/elf-${cc}-stack-protector.a" copy.o
done
popd 1>/dev/null

pushd "$OUT"
for elf in elf-*; do
  basename="${elf#"elf-"}"
  (hardening-check "$elf" > "hc-no-flags-${basename}"; echo $? > "hc-no-flags-${basename}.exit") || true
  (hardening-check -c -p -s -f -r -b "$elf" > "hc-all-flags-${basename}"; echo $? > "hc-all-flags-${basename}.exit") || true
  #objdump -Dr "$elf" > "objdump-${basename}"
  #readelf -Wa "$elf" > "readelf-${basename}"
done 1>/dev/null
