#!/bin/bash -eux

pushd build
for elf in elf-*; do
  basename="${elf#"elf-"}"
  diff "hc-no-flags-${basename}" <(cargo run -q -- "$elf")
  diff "hc-all-flags-${basename}" <(cargo run -q -- -c -p -s -f -r -b "$elf")
done
popd 1>/dev/null
